import { Outfit,Ovo } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
  weight:["400", "500", "600",'700'],
});

const ovo = Ovo({
  subsets: ["latin"],
  weight:["400"],
});

export const metadata = {
  title: "My personal portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // 'dark' here triggers the selector strategy defined in your globals.css
    <html lang="en" className="scroll-smooth ">
      <body
        className={`${outfit.variable} ${ovo.variable}`}
      >
        {children}
      </body>
    </html>
  );
}